export const config = {
   RPC_URL: 'https://namada.redbelly.xyz',
   REST_URL: 'https://namada.redbelly.xyz',
   EXPLORER_URL: 'https://explorer.redbelly.xyz/',
   STAKING_URL: 'https://flix.omniflix.co/stake',
   NETWORK_NAME: 'Namada',
   NETWORK_TYPE: 'testnet',
   CHAIN_ID: 'shielded-expedition.88f17d1d14',
   CHAIN_NAME: 'Shielded Expedition',
   COIN_DENOM: 'NAAN',
   COIN_MINIMAL_DENOM: 'unaan',
   COIN_DECIMALS: 6,
   PREFIX: '-',
   GAS_PRICE_STEP_LOW: 0.0025,
   GAS_PRICE_STEP_AVERAGE: 0.025,
   GAS_PRICE_STEP_HIGH: 0.04,
   FEATURES: ['stargate', 'ibc-transfer', 'no-legacy-stdTx', 'ibc-go'],
};
